repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
        args: ["--allow-unstaged-changes"]
      - id: end-of-file-fixer
        args: ["--allow-unstaged-changes"]
